# Generated by Django 3.0.5 on 2020-09-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200907_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approved',
            field=models.CharField(blank=True, default='No', max_length=10, null=True),
        ),
    ]
