from django.contrib import admin
from django.urls import path
from website import views
from django.contrib.auth import views as auth_views
from .views import VerificationView

urlpatterns = [
  path('',views.index,name="home"),
  path('terms_of_use',views.terms,name="terms-of-use"),
  path('privacy_policy',views.privacy,name="privacy-policy"),
  path('disclaimer',views.disclaimer,name="disclaimer"),
  path('return_policy',views.returnpolicy,name="return-policy"),
  path('signupuser',views.signupuserval,name="signupuser"),
  path('loginuser',views.loginuserval,name="loginuserval"),
  path('logout',views.logoutuser,name="logout"),
  path('activate/<uidb64>/<token>',VerificationView.as_view(),name="activate"),
  path('reset_password',auth_views.PasswordResetView.as_view(template_name="password_reset.html"),name="reset_password"),
  path('reset_password_sent',views.resetpassworddone,name="password_reset_done"),
  path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="change-password.html"),name="password_reset_confirm"),
  path('reset_password_complete',auth_views.PasswordResetCompleteView.as_view(template_name="reset-done.html"),name="password_reset_complete"),
  path('profile_details',views.profile,name="profile"),
  path('profile_update',views.profileupdate,name="profile-update"),
  path('profile_reupdate',views.profilereupdate,name="profile-reupdate"),
  path('product_upload_page',views.product_upload_page,name="product_upload1"),
  path('become_a_seller',views.sellerpage,name="seller-page"),
  path('register_as_seller',views.sellerregisterpage,name="seller-regitser"),
  path('register_seller',views.registerseller,name="register-seller"),
  path('seller_dashboard',views.sellerdashboard,name="seller-dashboard"),
  path('seller_search',views.sellersearch,name="seller-search"),
  path('seller_account',views.selleraccount,name="seller-account"),
  path('orders',views.sellerorders,name="seller-orders"),
  path('order_packed',views.orderpacked,name="order-packed"),
  path('returns',views.sellerreturns,name="seller-returns"),
  path('upload_product',views.uploadproduct,name="upload-product"),
  path('edit_product/<int:pk>',views.productedit,name="product-edit"),
  path('product_edit',views.editproduct,name="edit-product"),
  path('delete_product',views.deleteproduct,name="delete-product"),
  path('add_stock/<int:pk>',views.addstock,name="add-stock"),
  path('marketplace',views.marketplace,name="marketplace"),
  path('sports_collection',views.sportscollection,name="sports-collection"),
  path("women's_collection",views.womencollection,name="women-collection"),
  path('formal_collection',views.formalcollection,name="formal-collection"),
  path('view_product/<int:pk>',views.viewproduct,name="view-product"),
  path('ratenreview',views.ratenreview,name="ratenreview"),
  path('search',views.search,name="search"),
  path('footwears_and_apparels',views.footwearsnapparels,name="footwears-and-apparels"),
  path('fashion_clothing',views.fashionclothing,name="fashion-clothing"),
  path('checkout_page',views.checkout,name="checkout"),
  path('checkout_done',views.checkoutdone,name="checkout-done"),
  path('my_orders',views.myorders,name="my-orders"),
  path('track_order/<int:pk>',views.ordertracker,name="track-order"),
  path('return_item/<int:pk>',views.orderreturn,name="return-order"),
  path('my_returns',views.myreturns,name="my-returns"),
  path('cancel_return/<int:pk>',views.cancelreturn,name="cancel-return"),
  path('admin_control_panel_trikada',views.admincontrol,name="admin-control"),
  path('clear_orders',views.clearorder,name="clear-orders"),
  path('picked_order',views.pickedorder,name="picked-order"),
  path('admin_order_packed',views.adminorderpacked,name="admin-order-packed"),
  path('update_status_delivered',views.adminupdatedelivered,name="admin-update-delivered"),
  path('admin_returns',views.adminreturns,name="admin-returns"),
  path('approve_sellers',views.approvesellers,name="approve-sellers"),
  path('clear_payments',views.payments,name="payments"),
  path('confirm_product',views.confirmproduct,name="confirm-products"),
  path('feedback',views.feedback,name="feedback"),
  ]